// src/lib/components/custom-comps/footer.svelte
<script lang="ts">
	import BlueskyIcon from './bluesky-icon.svelte';
	import { BLUESKY_LOGO_HREF } from '$lib/constants';
	import GithubIcon from './github-icon.svelte';
	import { GITHUB_LOGO_HREF } from '$lib/constants';
</script>

<footer id="footer">
	<div class="mb-2 mt-4">
		<div class="flex flex-row items-center justify-center space-x-4">
			<BlueskyIcon href={BLUESKY_LOGO_HREF} width={30} height={30} />
			<GithubIcon href={GITHUB_LOGO_HREF} width={30} height={30} />
		</div>
	</div>
</footer>

// archive/src/components/footer.tsx
'use client';
import React from 'react';
import { GithubIcon } from 'lucide-react';
import BskyLogo from './bsky-logo';

const Footer = () => {
	return (
		<div className="items-centertext-black mb-2 mt-2 flex justify-center">
			<div className="flex items-center px-4 py-0">
				<a href="https://bsky.app/profile/montepy.in" target="_blank" rel="noopener noreferrer">
					<BskyLogo width={30} height={30} />
				</a>
			</div>
			<div className="flex items-center px-4 py-0">
				<a
					href="https://github.com/mohit2152sharma/bsky-projects"
					target="_blank"
					rel="noopener noreferrer"
				>
					<GithubIcon width={30} height={30} />
				</a>
			</div>
		</div>
	);
};

export default Footer;
